#!/bin/bash

# species_ninon: raw file, 
#               one path per line pointing to tsv files 
#               generated by Marie Petitjean  using Diamond V. 0.9.22
# clusters: 
species_ninon='/home/ninon.robin/Methode_Generic/data/sort_species_ninon.txt'
cluster='/home/ninon.robin/Methode_Generic/data/clusters.txt'

species=$(cat ${species_ninon} | sed 's/^\/.*\/.*\/.*\//,/g' | sed 's/.tsv//g') 
echo -n -e 'SPECIES'${species}\\\n | sed 's/ //g' > /home/ninon.robin/Methode_Generic/output/species.tsv
centroid=$(cat ${cluster} | cut -f 10 | sort | uniq)

for centro in $(echo ${centroid})
do
    echo ${centro} >> /home/ninon.robin/Methode_Generic/output/centro.tsv
    query=$(cat ${cluster} | grep ${centro} | cut -f 9 | sort | uniq)
    query=$(echo ${query} | sed 's/ /|/g')

    for path in $(cat ${species_ninon})  
    do 
        match=$(cut -f 1 ${path} | grep -E -c ${query})

        if [ ${match} != 0 ]
        then 
            match=1
        fi

        echo -n ,${match} >> /home/ninon.robin/Methode_Generic/output/share.tsv
    done 

    printf \\\n >> /home/ninon.robin/Methode_Generic/output/share.tsv
done 

centro='/home/ninon.robin/Methode_Generic/output/centro.tsv'
species='/home/ninon.robin/Methode_Generic/output/species.tsv'
share='/home/ninon.robin/Methode_Generic/output/share.tsv'

cat ${species} > /home/ninon.robin/Methode_Generic/output/matrix.tsv
paste ${centro} ${share} | sed 's/\t//g' >> /home/ninon.robin/Methode_Generic/output/matrix.tsv